# Generated by Django 5.2.17 on 2026-09-05 14:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clause',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_order', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=100)),
                ('role_code', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('PENDING', '待处理'), ('APPROVED', '已通过'), ('REJECTED', '已驳回'), ('CANCELLED', '已取消')], default='PENDING', max_length=16)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['step_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('PENDING', '待处理'), ('APPROVED', '已通过'), ('REJECTED', '已驳回'), ('CANCELLED', '已取消')], max_length=16)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='contracts.approvaltask')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('previous_hash', models.CharField(blank=True, max_length=64)),
                ('event_hash', models.CharField(editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClauseVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=32)),
                ('content', models.TextField()),
                ('is_core', models.BooleanField(default=False)),
                ('risk_level', models.CharField(choices=[('LOW', '低风险'), ('MEDIUM', '中风险'), ('HIGH', '高风险')], default='MEDIUM', max_length=16)),
                ('content_hash', models.CharField(editable=False, max_length=64)),
                ('clause', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='contracts.clause')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_clause_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['clause__code', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('counterparty', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('IN_REVIEW', '审核中'), ('APPROVED', '已审核'), ('REJECTED', '已驳回'), ('SIGNED', '已签署'), ('ARCHIVED', '已归档')], default='DRAFT', max_length=16)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency', models.CharField(default='CNY', max_length=8)),
                ('risk_level', models.CharField(blank=True, choices=[('LOW', '低风险'), ('MEDIUM', '中风险'), ('HIGH', '高风险')], max_length=16)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('PUBLISHED', '已发布'), ('RETIRED', '已停用')], default='DRAFT', max_length=16)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ContractVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_no', models.PositiveIntegerField()),
                ('snapshot', models.JSONField(default=dict)),
                ('source_file', models.FileField(blank=True, null=True, upload_to='contracts/%Y/%m/')),
                ('content_hash', models.CharField(editable=False, max_length=64)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('is_final', models.BooleanField(default=False)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='contracts.contract')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_contract_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['contract', '-version_no'],
            },
        ),
        migrations.CreateModel(
            name='ReviewCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', '待处理'), ('IN_PROGRESS', '审核中'), ('COMPLETED', '已完成'), ('REJECTED', '已驳回')], default='PENDING', max_length=16)),
                ('risk_level', models.CharField(choices=[('LOW', '低风险'), ('MEDIUM', '中风险'), ('HIGH', '高风险')], max_length=16)),
                ('summary', models.TextField(blank=True)),
                ('rule_set_version', models.CharField(default='2026.09.1', max_length=32)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('contract_version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review_case', to='contracts.contractversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='approvaltask',
            name='review_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='contracts.reviewcase'),
        ),
        migrations.CreateModel(
            name='RiskFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('RULE', '规则'), ('DIFF', '比对'), ('AI', 'AI')], max_length=16)),
                ('severity', models.CharField(choices=[('LOW', '低风险'), ('MEDIUM', '中风险'), ('HIGH', '高风险')], max_length=16)),
                ('clause_code', models.CharField(blank=True, max_length=64)),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField()),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('review_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='contracts.reviewcase')),
            ],
            options={
                'ordering': ['-severity', 'clause_code'],
            },
        ),
        migrations.CreateModel(
            name='TemplateVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('PUBLISHED', '已发布'), ('RETIRED', '已停用')], default='DRAFT', max_length=16)),
                ('change_note', models.TextField(blank=True)),
                ('guidance', models.TextField(blank=True)),
                ('risk_notice', models.TextField(blank=True)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_template_versions', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='contracts.contracttemplate')),
            ],
            options={
                'ordering': ['template__code', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateClause',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('required', models.BooleanField(default=True)),
                ('locked', models.BooleanField(default=False)),
                ('clause_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contracts.clauseversion')),
                ('template_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_clauses', to='contracts.templateversion')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='template_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='contracts.templateversion'),
        ),
        migrations.CreateModel(
            name='VariableDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=64)),
                ('label', models.CharField(max_length=100)),
                ('data_type', models.CharField(choices=[('TEXT', '文本'), ('NUMBER', '数字'), ('MONEY', '金额'), ('DATE', '日期'), ('ENUM', '枚举')], default='TEXT', max_length=16)),
                ('required', models.BooleanField(default=False)),
                ('validation', models.JSONField(blank=True, default=dict)),
                ('template_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='contracts.templateversion')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.AddConstraint(
            model_name='clauseversion',
            constraint=models.UniqueConstraint(fields=('clause', 'version'), name='unique_clause_version'),
        ),
        migrations.AddConstraint(
            model_name='contractversion',
            constraint=models.UniqueConstraint(fields=('contract', 'version_no'), name='unique_contract_version'),
        ),
        migrations.AddConstraint(
            model_name='templateversion',
            constraint=models.UniqueConstraint(fields=('template', 'version'), name='unique_template_version'),
        ),
        migrations.AddConstraint(
            model_name='templateclause',
            constraint=models.UniqueConstraint(fields=('template_version', 'clause_version'), name='unique_clause_in_template_version'),
        ),
        migrations.AddConstraint(
            model_name='templateclause',
            constraint=models.UniqueConstraint(fields=('template_version', 'sequence'), name='unique_clause_sequence_in_template'),
        ),
        migrations.AddConstraint(
            model_name='variabledefinition',
            constraint=models.UniqueConstraint(fields=('template_version', 'key'), name='unique_variable_in_template_version'),
        ),
    ]
